{
  'en':
    {
      'login_success': 'Login successful',
      'logout_success': 'Logout successful',
      'session_closed_success': 'Session closed successfully',

      # Error messages,,,
      'login_failure': 'Invalid username or password',
      'session_expired': 'Session expired, please log in again',
      'session_required': 'Session required to access this resource',
      'invalid_session': 'Invalid session, please log in again',
      'user_not_found': 'User not found',
      'server_error': 'An error occurred on the server, please try again later',
    },
  'es':
    {
      'login_success': 'Inicio de sesión exitoso',
      'logout_success': 'Cierre de sesión exitoso',
      'session_closed_success': 'Sesión cerrada exitosamente',

      # Mensajes de error
      'login_failure': 'Nombre de usuario o contraseña inválidos',
      'session_expired': 'Sesión expirada, por favor inicia sesión nuevamente',
      'session_required': 'Se requiere sesión para acceder a este recurso',
      'invalid_session': 'Sesión inválida, por favor inicia sesión nuevamente',
      'user_not_found': 'Usuario no encontrado',
      'server_error': 'Ocurrió un error en el servidor, por favor intenta nuevamente más tarde',
    }
}
