version: '3.8'

services:
  db:
    image: postgres:16
    container_name: webii_db
    environment:
      POSTGRES_DB: webii
      POSTGRES_USER: webii_user
      POSTGRES_PASSWORD: webii_pass
    ports:
      - '5436:5432'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./restore.sql/initial_data.sql:/docker-entrypoint-initdb.d/02-data.sql
      - ./backups:/backups
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost',
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  db_ready:
    image: postgres:16
    container_name: webii_db_ready
    depends_on:
      - db
    environment:
      POSTGRES_DB: webii
      POSTGRES_USER: webii_user
      POSTGRES_PASSWORD: webii_pass
    command: >
      bash -c "
        until pg_isready -h db -U $${POSTGRES_USER} -d $${POSTGRES_DB}; do
          echo 'Esperando a que la base de datos esté lista...';
          sleep 2;
        done;
        echo 'Base de datos lista, actualizada y en ejecución.';
      "
    restart: 'no'

  pgadmin:
    image: dpage/pgadmin4
    container_name: webii_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data:
