version: '3.8'

services:
  db:
    image: postgres:16
    container_name: webii_db
    environment:
      POSTGRES_DB: webii
      POSTGRES_USER: webii_user
      POSTGRES_PASSWORD: webii_pass
    ports:
      - "5436:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./restore.sql/initial_data.sql:/docker-entrypoint-initdb.d/02-data.sql
      - ./backups:/backups
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: webii_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: